### ISSUE TITLE
Data update doesn't deploy latest commit

### ISSUE THREAD

**Issue by juberti** [fixie-ai/thefastest.ai#10]
See https://github.com/fixie-ai/thefastest.ai/actions/runs/8861441816/job/24333320169, latest.json is updated by the benchmark run via commit b25ac6d2e794128310510304738a4b21eaa9432e, but the commit pushed to prod is the previous one, ae40ed9347e1030b5dc8de87ad6db7d4b35eeea3. 

Not sure if we need a sleep, or maybe a specific commit id, or perhaps just don't checkout if the repo is already checked out when running the action.

**Comment by juberti** [comment]
I think this explains some of the stale data issues we've been seeing.

**Comment by benlower** [comment]
nice find. will take a look.

**Comment by juberti** [comment]
is this fixed now?
