### ISSUE TITLE
have you tried tenstorrent card based inference?

### ISSUE THREAD

**Issue by arjunkrishna** [fixie-ai/thefastest.ai#11]
I am trying to figure out if tenstorrent cards also provide the same throughput for fraction of the groq accerator cards. I do not see many comparisons. 

groq accerator card.. it seems they are 20k each
https://www.mouser.com/ProductDetail/BittWare/RS-GQ-GC1-0109?qs=ST9lo4GX8V2eGrFMeVQmFw%3D%3D

tenstorrent grayskull cards.. it seems like they are around $700 each.
https://tenstorrent.com/cards/

if you have access to such setup then adding tenstorrent based testing would be good. then home users can try out such a card for home use as well.

**Comment by juberti** [comment]
FLOPs seem similar, grayskull seems to have more memory. This isn't something we could take on as there's probably a fair amount of work to get a model to work well on the card, but I'm guessing that we might see someone stand up a service using these cards.

**Comment by juberti** [comment]
Closing, will revisit if we see a provider with this hardware.
