### ISSUE TITLE
OVHcloud AI Endpoints benchmark

### ISSUE THREAD

**Issue by Joffref** [fixie-ai/thefastest.ai#24]
Recently [OVHcloud](https://www.ovhcloud.com/fr/), released a new product called [AI Endpoints](https://endpoints.ai.cloud.ovh.net/). 

This product offers LLM on the shelf with a OpenAI compatible API. 

For example, you can call Mixtral-8x22b using the following code snippet:

```bash
curl -X 'POST' \
  'https://mixtral-8x22b-instruct-v01.endpoints.kepler.ai.cloud.ovh.net/api/openai_compat/v1/chat/completions' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "max_tokens": 100,
  "messages": [
    {
      "content": "Hello, how are you today?",
      "name": "John",
      "role": "user"
    }
  ]
}'
```

That'd be amazing to see it benched! I'd love to contribute to bring this feature up, how could I do?

**Comment by Joffref** [comment]
For more context, there are the following models exposed through this service:
- Mistral-7B-Instruct v0.2 https://mistral-7b-instruct-v02.endpoints.kepler.ai.cloud.ovh.net/
- CodeLlama-13b-Instruct-hf v1.0 https://codellama-13b-instruct-hf.endpoints.kepler.ai.cloud.ovh.net
- Mixtral-8x7b-instruct v0.1 https://mixtral-8x7b-instruct-v01.endpoints.kepler.ai.cloud.ovh.net/
- Mixtral-8x22b-Instruct v1.0 https://mixtral-8x22b-instruct-v01.endpoints.kepler.ai.cloud.ovh.net/
- Llama-3-70B-Instruct v1.0 https://llama-3-70b-instruct.endpoints.kepler.ai.cloud.ovh.net/
- Llama-3-8B-Instruct v1.0 https://llama-3-8b-instruct.endpoints.kepler.ai.cloud.ovh.net/
- Llama-2-13b-chat-hf v1.0 https://llama-2-13b-chat-hf.endpoints.kepler.ai.cloud.ovh.net

**Comment by juberti** [comment]
If it's OpenAI-compatible then all that's needed is to add entries for the desired models (I'd suggest the Llama 3 variants to start) to `llm_benchmark_suite.py` and generation of an API key that we can use in our runner.

**Comment by juberti** [comment]
hmm, looks like an API key isn't actually needed. Added in https://github.com/fixie-ai/ai-benchmarks/pull/78, should start showing up in stats tomorrow (2024-06-12)

**Comment by Joffref** [comment]
Awesome work done here, it's been a few days I'm daily watching those metrics. Have you any idea why, when I'm clicking on ovh.net, it redirects me to a sort of speedtest instead of the official website? :+1:

**Comment by juberti** [comment]
It's just sending you to https://ovh.net, if there's another link we should use instead just LMK.

**Comment by Joffref** [comment]
I think you should use https://endpoints.ai.cloud.ovh.net/ instead.

**Comment by juberti** [comment]
Care to make a PR? Just change line 207 here: https://github.com/fixie-ai/ai-benchmarks/pull/78/files
