### ISSUE TITLE
Europe (Paris) leaderboard not working

### ISSUE THREAD

**Issue by ghost** [fixie-ai/thefastest.ai#39]
Navigating to `https://thefastest.ai/?r=cdg` doesn't seem to be working currently.

![image](https://github.com/user-attachments/assets/7e1254e2-893f-4bd3-96e9-13035785b4dc)

**Comment by juberti** [comment]
Try again now, there was a failure but I kicked off a new run right before you posted this

**Comment by ghost** [comment]
Cool thanks! 

@juberti any interest in adding a Asia region test?
