### ISSUE TITLE
standardize model names/add filtering

### ISSUE THREAD

**Issue by beaugunderson** [fixie-ai/thefastest.ai#5]
it's super hard to compare speeds because not all providers support all models... if I want to compare just llama3-70b speeds for example I tried sorting by model name... I end up with one option at the top of the list (because the L is capitalized) and some options at the bottom but not located next to each other because one uses "llama3" and the other "llama-3". standardizing the names + adding filtering on the model would make it much easier

**Comment by juberti** [comment]
yeah, good point, we'll see what we can do here. You can try this query for now: https://thefastest.ai?mf=3-70

**Comment by juberti** [comment]
Standardized model names as requested. Try https://thefastest.ai/?mf=llama-3-70b

**Comment by beaugunderson** [comment]
Perfect, thanks for doing that!
